//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DesktopNote.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DesktopNote.Resources.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string button_cancel {
            get {
                return ResourceManager.GetString("button_cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        public static string button_ok {
            get {
                return ResourceManager.GetString("button_ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string button_search {
            get {
                return ResourceManager.GetString("button_search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notes here..
        /// </summary>
        public static string default_note_text {
            get {
                return ResourceManager.GetString("default_note_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search for.
        /// </summary>
        public static string label_search_for {
            get {
                return ResourceManager.GetString("label_search_for", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto Dock.
        /// </summary>
        public static string menu_auto_dock {
            get {
                return ResourceManager.GetString("menu_auto_dock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto Start.
        /// </summary>
        public static string menu_auto_start {
            get {
                return ResourceManager.GetString("menu_auto_start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        public static string menu_exit {
            get {
                return ResourceManager.GetString("menu_exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help.
        /// </summary>
        public static string menu_help {
            get {
                return ResourceManager.GetString("menu_help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paper Color.
        /// </summary>
        public static string menu_paper_color {
            get {
                return ResourceManager.GetString("menu_paper_color", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset Formats.
        /// </summary>
        public static string menu_reset_formats {
            get {
                return ResourceManager.GetString("menu_reset_formats", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset Settings.
        /// </summary>
        public static string menu_reset_settings {
            get {
                return ResourceManager.GetString("menu_reset_settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Available editing features can be accessd from menu or keyboard combination.
        ///Use Ctrl + mouse wheel to change font size.
        ///Change font or font size when there is a selection will only change selected text.
        ///Note content will be auto saved to application root.
        ///You will be directed to the homepage if you click OK..
        /// </summary>
        public static string msgbox_help {
            get {
                return ResourceManager.GetString("msgbox_help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was an error loading the note contents. Please refer to the following backup file at application root for recovery..
        /// </summary>
        public static string msgbox_load_error {
            get {
                return ResourceManager.GetString("msgbox_load_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please do not run this program from a network location. Copy to a local drive first.
        ///Program will exit now..
        /// </summary>
        public static string msgbox_run_from_network {
            get {
                return ResourceManager.GetString("msgbox_run_from_network", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search has reached the end of the document..
        /// </summary>
        public static string msgbox_searched_to_end {
            get {
                return ResourceManager.GetString("msgbox_searched_to_end", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading Notes Failed.
        /// </summary>
        public static string msgbox_title_load_error {
            get {
                return ResourceManager.GetString("msgbox_title_load_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save failed.
        /// </summary>
        public static string status_save_failed {
            get {
                return ResourceManager.GetString("status_save_failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saved.
        /// </summary>
        public static string status_saved {
            get {
                return ResourceManager.GetString("status_saved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Align Center (Ctrl + E).
        /// </summary>
        public static string tooltip_align_center {
            get {
                return ResourceManager.GetString("tooltip_align_center", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Align Justify (Ctrl + J).
        /// </summary>
        public static string tooltip_align_justify {
            get {
                return ResourceManager.GetString("tooltip_align_justify", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Align Left (Ctrl + L).
        /// </summary>
        public static string tooltip_align_left {
            get {
                return ResourceManager.GetString("tooltip_align_left", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Align Right (Ctrl + R).
        /// </summary>
        public static string tooltip_align_right {
            get {
                return ResourceManager.GetString("tooltip_align_right", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back Color.
        /// </summary>
        public static string tooltip_back_color {
            get {
                return ResourceManager.GetString("tooltip_back_color", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bold (Ctrl + B).
        /// </summary>
        public static string tooltip_bold {
            get {
                return ResourceManager.GetString("tooltip_bold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bullets (Ctrl + Shift + L).
        /// </summary>
        public static string tooltip_bullets {
            get {
                return ResourceManager.GetString("tooltip_bullets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy (Ctrl + C).
        /// </summary>
        public static string tooltip_copy {
            get {
                return ResourceManager.GetString("tooltip_copy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cut (Ctrl + X).
        /// </summary>
        public static string tooltip_cut {
            get {
                return ResourceManager.GetString("tooltip_cut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Decrease Indent (Ctrl + Shift + T).
        /// </summary>
        public static string tooltip_decrease_indent {
            get {
                return ResourceManager.GetString("tooltip_decrease_indent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Decrease Size (Ctrl + Mousewheel Down).
        /// </summary>
        public static string tooltip_decrease_size {
            get {
                return ResourceManager.GetString("tooltip_decrease_size", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find (Ctrl + F).
        /// </summary>
        public static string tooltip_find {
            get {
                return ResourceManager.GetString("tooltip_find", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Font Color.
        /// </summary>
        public static string tooltip_font_color {
            get {
                return ResourceManager.GetString("tooltip_font_color", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Font (Default).
        /// </summary>
        public static string tooltip_font_default {
            get {
                return ResourceManager.GetString("tooltip_font_default", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Font (Selection).
        /// </summary>
        public static string tooltip_font_selection {
            get {
                return ResourceManager.GetString("tooltip_font_selection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Highlight (Ctrl + H).
        /// </summary>
        public static string tooltip_highlight {
            get {
                return ResourceManager.GetString("tooltip_highlight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Increase Indent (Ctrl + T).
        /// </summary>
        public static string tooltip_increase_indent {
            get {
                return ResourceManager.GetString("tooltip_increase_indent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Increase Size (Ctrl + Mousewheel Up).
        /// </summary>
        public static string tooltip_increase_size {
            get {
                return ResourceManager.GetString("tooltip_increase_size", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Italic (Ctrl + I).
        /// </summary>
        public static string tooltip_italic {
            get {
                return ResourceManager.GetString("tooltip_italic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Numbering (Ctrl + Shift + N).
        /// </summary>
        public static string tooltip_numbering {
            get {
                return ResourceManager.GetString("tooltip_numbering", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paste (Ctrl + V).
        /// </summary>
        public static string tooltip_paste {
            get {
                return ResourceManager.GetString("tooltip_paste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paste Text Only (Ctrl + Shift + V).
        /// </summary>
        public static string tooltip_paste_text {
            get {
                return ResourceManager.GetString("tooltip_paste_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Redo (Ctrl + Y).
        /// </summary>
        public static string tooltip_redo {
            get {
                return ResourceManager.GetString("tooltip_redo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Strike-through (Ctrl + D).
        /// </summary>
        public static string tooltip_strikethrough {
            get {
                return ResourceManager.GetString("tooltip_strikethrough", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Underline (Ctrl + U).
        /// </summary>
        public static string tooltip_underline {
            get {
                return ResourceManager.GetString("tooltip_underline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Undo (Ctrl + Z).
        /// </summary>
        public static string tooltip_undo {
            get {
                return ResourceManager.GetString("tooltip_undo", resourceCulture);
            }
        }
    }
}
